import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";
import Footer from "./component/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-11/12 mx-auto my-2">
          <Navbar></Navbar>
        </nav>
        <main className="md:w-11/12 mx-auto my-2 min-h-[calc(100vh-235px)]">
          {children}
        </main>
        <footer><Footer></Footer></footer>
      </body>
    </html>
  );
}
